version: '3.3'
services:
  server:
     restart: always
     image: nginx
     volumes:
      - ./src/app/key.key:/etc/ssl/key.key
      - ./src/app/crt.crt:/etc/ssl/crt.crt
      - ./src/server/conf.d:/etc/nginx/conf.d
      - ./src/app:/app
     links:
      - web:web
     ports:
      - "80:80"
      - "443:443"

  redis:
    image: "redis:alpine"
    expose:
        - 6379
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

  web:
    build: ./srs
    command: bash -c 'gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000'
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SUPERUSER_NAME=${SUPERUSER_NAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - AWS_URI=${AWS_URI}
      - AWS_ACCCESS_KEY=${AWS_ACCCESS_KEY}
      - AWS_SERVICE_NAME=${AWS_SERVICE_NAME}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
    ports:
      - 8555:8000
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
